### ISSUE TITLE
The code seems incomplete

### ISSUE THREAD

**Issue by znagzanglong** [lyh6560new/BotMoE#3]
After installing the requirements and trying to run it, something like this happened.
Traceback (most recent call last):
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\main.py", line 239, in <module>
    logger=set_logger(file[idx],exp_name)
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\utils.py", line 39, in set_logger
    handler = logging.FileHandler(root+file)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\logging\__init__.py", line 1147, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\logging\__init__.py", line 1176, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\kust\\xuesu\\code\\BotMoE-main\\BotMoE-main\\MoE\\mixture-of-experts\\twibot-20\\AllInOne1_rgcn_rgt_gcn.log'

**Comment by lyh6560new** [comment]
you need to change the log path to your own
