### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (447334x5 and 9x128)

### ISSUE THREAD

**Issue by znagzanglong** [lyh6560new/BotMoE#7]
I got this error when I tried to run

Traceback (most recent call last):
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\main.py", line 267, in <module>
    trainer.train()
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\main.py", line 138, in train
    output,exp_loss = self.model(batch.des_embedding,batch.tweet_embedding,batch.num_property_embedding,batch.cat_property_embedding,batch.num_for_h,batch.edge_index,batch.edge_type)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\ThreeInONE.py", line 580, in forward
    des_tensor,tweets_tensor,num_prop,category_prop,num_for_h=self.align(des_tensor,tweets_tensor,num_prop,category_prop,num_for_h)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\kust\xuesu\code\BotMoE-main\BotMoE-main\ThreeInONE.py", line 37, in forward
    self.linear_relu_num_prop(num_prop),self.linear_relu_cat_prop(category_prop),self.linear_num_for_h_prop(num_for_h)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\container.py", line 141, in forward
    input = module(input)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\modules\linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "C:\Users\Administrator\anaconda3\envs\FedAck\lib\site-packages\torch\nn\functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (447334x5 and 9x128)

**Comment by nbritt27** [comment]
I'm getting this same error, using the default Twibot-20 processed file. Using my own preprocessed version of Cresci returns a similar error, just with a 3x1 non-multiplication error. Changing the number 
 of inputs in the second layer solves the error, but I'd rather not change the model. I also get an issue of the category MoE having a size much greater than the other two following this. I see that the issue is closed, any update that I'm missing?

**Comment by yasmeenhany** [comment]
hello! I see this issue was closed. Can you share what the fix was?

**Comment by yasmeenhany** [comment]
Update: the issue was fixed by replacing `9` with `5` in `feature_align` ThreeInONE.py below 
`        self.linear_num_for_h_prop=nn.Sequential(
            nn.Linear(9,int(align_size)),
            nn.LeakyReLU()
        )`
